fetch("https://dummyjson.com/users")
  .then((res) => res.json())
  .then((usersData) => fetch(`https://dummyjson.com/posts/user/${usersData.users[0].id}`))
  .then((res) => res.json())
  .then((postsData) => fetch(`https://dummyjson.com/comments/post/${postsData.posts[0].id}`))
  .then((res) => res.json())
  .then((commentsData) => fetch(`https://dummyjson.com/users/${commentsData.comments[0].user.id}`))
  .then((res) => res.json())
  .then((userData) => console.log(userData))
  .catch((err) => console.log(err));
